dist: bionic
language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: test
      name: "Run tests"
      script:
        - "./gradlew test"

    - stage: publish
      name: Publish
      if: branch=eloy-fer-form3-patch AND tag IS present
      skip_cleanup: true
      script:
        - "./gradlew publishMavenPublicationToForm3releasesRepository"


